# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargarPdfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odc1', models.FileField(upload_to='cargarpdfs/')),
                ('odc2', models.FileField(blank=True, null=True, upload_to='cargarpdfs/')),
                ('odc3', models.FileField(blank=True, null=True, upload_to='cargarpdfs/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PrimerRegistro')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='segundoregistro',
            name='caratula',
            field=models.FileField(blank=True, null=True, upload_to='caratula/'),
        ),
        migrations.AlterField(
            model_name='segundoregistro',
            name='tarjeta_de_mejoravit',
            field=models.FileField(blank=True, null=True, upload_to='targeta_infonavit/'),
        ),
    ]
