# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionAsesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_t', models.PositiveIntegerField()),
                ('ref_p', models.CharField(max_length=20, verbose_name='Referencia de Pago')),
                ('crdb_rpago', models.BooleanField()),
                ('opereacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RelacionP')),
            ],
        ),
    ]
