# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comisionasesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comisionasesor',
            old_name='opereacion',
            new_name='operacion',
        ),
    ]
