# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160224_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisionasesor',
            name='operacion',
        ),
        migrations.AddField(
            model_name='comisionasesor',
            name='operacions',
            field=models.ManyToManyField(to='app.RelacionP'),
        ),
        migrations.AlterField(
            model_name='comisionasesor',
            name='crdb_rpago',
            field=models.BooleanField(verbose_name='Cheque Cobrado'),
        ),
    ]
