# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160212_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerregistro',
            name='ife',
            field=models.FileField(blank=True, null=True, upload_to='ifes/'),
        ),
    ]
