# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20160225_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionasesor',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
