# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160212_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerregistro',
            name='ife',
        ),
        migrations.AddField(
            model_name='segundoregistro',
            name='ife',
            field=models.FileField(blank=True, null=True, upload_to='ifes/'),
        ),
    ]
