# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comisionasesor_asesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionasesor',
            name='crdb_rpago',
            field=models.BooleanField(default=False, verbose_name='Cheque Cobrado'),
        ),
    ]
