# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160213_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerregistro',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
