# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_comisionasesor_operacions'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionasesor',
            name='fecha',
            field=models.DateField(default='2016-02-23'),
            preserve_default=False,
        ),
    ]
