# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comisionasesor_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionasesor',
            name='ref_p',
            field=models.CharField(max_length=20, null=True, verbose_name='Referencia de Pago'),
        ),
    ]
