# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160214_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionp',
            name='crbd_rpago',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
