# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160214_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionp',
            name='ref_pago',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Referencia de Pago'),
        ),
    ]
