# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160214_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionp',
            name='odc1p',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relacionp',
            name='odc2p',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relacionp',
            name='odc3p',
            field=models.BooleanField(default=False),
        ),
    ]
