# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160215_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundoregistro',
            name='caratula',
            field=models.FileField(blank=True, null=True, upload_to='guardar_caratula'),
        ),
        migrations.AlterField(
            model_name='segundoregistro',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.PrimerRegistro'),
        ),
        migrations.AlterField(
            model_name='segundoregistro',
            name='ife',
            field=models.FileField(blank=True, null=True, upload_to='guardar_ife'),
        ),
        migrations.AlterField(
            model_name='segundoregistro',
            name='tarjeta_de_mejoravit',
            field=models.FileField(blank=True, null=True, upload_to='guardar_tarjeta'),
        ),
    ]
