# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160316_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segundoregistro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PrimerRegistro'),
        ),
    ]
