# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='tipo',
            field=models.CharField(choices=[('1', 'Asesor'), ('2', 'Asistente'), ('3', 'Gael')], max_length=2),
        ),
    ]
