# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='clave',
        ),
        migrations.AddField(
            model_name='datos',
            name='claveinterb',
            field=models.CharField(default=11111111111, max_length=18, verbose_name='Clave Interbancaria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datos',
            name='num_de_cuenta',
            field=models.CharField(max_length=16),
        ),
    ]
