# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20160318_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatosSucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renta', models.DecimalField(decimal_places=2, max_digits=7)),
                ('luz', models.DecimalField(decimal_places=2, max_digits=7)),
                ('agua', models.DecimalField(decimal_places=2, max_digits=7)),
                ('varios', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='agua',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='luz',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='renta',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='varios',
        ),
        migrations.AddField(
            model_name='gatossucursal',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Sucursal'),
        ),
    ]
