# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20160318_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatossucursal',
            name='fecha',
            field=models.DateField(auto_now_add=True, default='2016-02-18'),
            preserve_default=False,
        ),
    ]
