# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_gatossucursal_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatossucursal',
            name='agua',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gatossucursal',
            name='fecha',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gatossucursal',
            name='luz',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gatossucursal',
            name='renta',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gatossucursal',
            name='telefono',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gatossucursal',
            name='varios',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
