# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20160318_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatossucursal',
            name='fecha',
            field=models.DateField(auto_now_add=True, default='2016-03-05'),
            preserve_default=False,
        ),
    ]
