# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20160318_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatossucursal',
            name='agua',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gatossucursal',
            name='luz',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
